language: node_js
node_js:
  - 10
install:
  - npm i
after_success:
  - mkdir dist
  - cp -R src/index.html src/js src/css src/img dist
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master